### ISSUE TITLE
Dead link in the "Featured Mods" page.

### ISSUE THREAD

**Issue by IoIxD** [minecraft-cursed-legacy/minecraft-cursed-legacy.github.io#3]
The link to the ModMenu port is a dead link. The release was removed and all of the .jar files on that mod's releases pages were also removed. Either a direct link to the .jar should be provided or that should be removed.

**Comment by IoIxD** [comment]
I got somebody to compile the mod for me, I can send it to anyone who asks over Discord. But it seems whoever made the mod does not want to be associated with the project anymore (despite keeping the github pages up) so I would guess that it should just be removed.

**Comment by valoeghese** [comment]
Yeah, Amb0s removed the download, they mentioned that they might reupload it I think but I can't check because they deleted like all their messages in most servers

**Comment by valoeghese** [comment]
should probably remove it

**Comment by valoeghese** [comment]
Though I believe station api still has a copy of the port
